# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-18 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_userdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'Дополнительно', 'verbose_name_plural': 'Дополнительно'},
        ),
        migrations.AddField(
            model_name='userdata',
            name='liked_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='order_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='owner_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
