# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
