# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePerSome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Цена за ...',
                'verbose_name_plural': 'Цены за ...',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_some',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.PricePerSome'),
        ),
    ]
