# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180124_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
